### ISSUE TITLE
Exception from navigation contributor: AngularNavigationContributor. The getter 'offset' was called on null.

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/angular_analyzer_plugin#120]
## Analyzer Feedback from IntelliJ
IDEA: 171.SNAPSHOT, Dart: 1.21.0-dev.11.1, Windows 10
## Stack

```dart
Dart analysis server, SDK version 1.21.0-dev.11.1, server version 1.17.0, error: Exception from navigation contributor: AngularNavigationContributor
NoSuchMethodError: The getter 'offset' was called on null.
Receiver: null
Tried calling: offset
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      AngularNavigationContributor._addDirectiveRegions (package:angular_analyzer_server_plugin/src/analysis.dart:94)
#3      AngularNavigationContributor.computeNavigation (package:angular_analyzer_server_plugin/src/analysis.dart:54)
#4      computeNavigation (package:analysis_server/src/domains/analysis/navigation.dart:28)
#5      sendAnalysisNotificationNavigation.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:203)
#6      _sendNotification.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:274)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#8      _sendNotification (package:analysis_server/src/operation/operation_analysis.dart:272)
#9      sendAnalysisNotificationNavigation (package:analysis_server/src/operation/operation_analysis.dart:201)
#10     AnalysisServer.setAnalysisSubscriptions.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1242)
#11     _HashMap.forEach (dart:collection-patch/collection_patch.dart:151)
#12     AnalysisServer.setAnalysisSubscriptions (package:analysis_server/src/analysis_server.dart:1219)
#13     AnalysisDomainHandler.setSubscriptions (package:analysis_server/src/domain_analysis.dart:307)
#14     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:220)
#15     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:864)
#16     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#17     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:860)
#18     _rootRun (dart:async/zone.dart:1150)
#19     _CustomZone.run (dart:async/zone.dart:1026)
#20     _CustomZone.runGuarded (dart:async/zone.dart:924)
#21     runZoned (dart:async/zone.dart:1501)
#22     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:859)
#23     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:170)
#24     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#25     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161)
#26     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110)
#27     _rootRunUnary (dart:async/zone.dart:1158)
#28     _CustomZone.runUnary (dart:async/zone.dart:1037)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#32     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#33     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#34     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#35     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:158)
#36     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:133)
#37     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#38     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#39     _rootRunUnary (dart:async/zone.dart:1158)
#40     _CustomZone.runUnary (dart:async/zone.dart:1037)
#41     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#42     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#43     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#44     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#45     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#46     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#47     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#48     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#49     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#50     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
#51     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#52     _rootRunUnary (dart:async/zone.dart:1158)
#53     _CustomZone.runUnary (dart:async/zone.dart:1037)
#54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#57     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#58     _StreamController._add (dart:async/stream_controller.dart:635)
#59     _StreamController.add (dart:async/stream_controller.dart:581)
#60     _Socket._onData (dart:io-patch/socket_patch.dart:1680)
#61     _rootRunUnary (dart:async/zone.dart:1162)
#62     _CustomZone.runUnary (dart:async/zone.dart:1037)
#63     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#64     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#65     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#66     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#67     _StreamController._add (dart:async/stream_controller.dart:635)
#68     _StreamController.add (dart:async/stream_controller.dart:581)
#69     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
#70     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:781)
#71     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#72     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#73     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#74     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

```

**Comment by MichaelRFairhurst** [comment]
Thanks for reporting!

Are you seeing any fallout issues from this? There's a strange backstory behind this which is that our code provides this data only for intelliJ to (currently) ignore it, thus navigation support not being in just yet. Failing to get the data might be harmless in this case.

Definitely should get solved. And priority will go up a lot of its causing any immediate issues.

**Comment by alexander-doroshko** [comment]
I cloned 7 projects from https://github.com/angular-examples/ and configured them as a single WebStorm project:
![image](https://cloud.githubusercontent.com/assets/4499789/20846199/95aae550-b8d9-11e6-93d4-99c36318cb98.png)
I'm getting a lot of errors and warnings in the Dart Analysis view with incorrect ranges, for example:
![image](https://cloud.githubusercontent.com/assets/4499789/20846458/bfb716c4-b8da-11e6-8c34-df6bb8ab0eeb.png)
And I got this exception when opened on of the files.

**Comment by alexander-doroshko** [comment]
Also I'm getting fatal errors from the analysis server, server is restarted but dies agail. Filed https://github.com/dart-lang/sdk/issues/27974, but may be it is caused by the angular_analyzer_plugin as well.

**Comment by scheglov** [comment]
I think this issue is unrelated to Angular.
And it's on my plate.

**Comment by MichaelRFairhurst** [comment]
That's an ugly file right there.

I think I know why its freaking out, but its certainly not clear why based on looking at that mess.

Currently we don't support pub transformers, and the open source projects that use pub usually rely on them to add `NgFor` etc to all the templates. Without `NgFor`, looks like the errors get gross.

I'm going to file a separate issue for the misaligned errors in your attached image, but make note that it might be fallout from this navigation bug.

**Comment by MichaelRFairhurst** [comment]
We don't yet analyze pubspecs, but it could definitely be something else specific to OS projects or to these seven projects interacting.

**Comment by MichaelRFairhurst** [comment]
Also: Just put it together that its you, Alex! Sorry for the whole intellij backstory thing that you already know!

Thanks for filing these bugs. I'm glad you were able to get working on things even though the projects were freaking out a bit...

**Comment by MichaelRFairhurst** [comment]
#187 merged
