### ISSUE TITLE
Error when binding contains "<"

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#204]
Super simple repro:

```
  {{<}}
```

The full scope of  what causes this and whether its common during edit workflows is unclear

stack trace:

```
NoSuchMethodError: The getter 'isDynamic' was called on null.
Receiver: null
Tried calling: isDynamic
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ResolverVisitor.visitListLiteral (package:analyzer/src/generated/resolver.dart:6234)
#3      ListLiteralImpl.accept (package:analyzer/src/dart/ast/ast.dart:6907)
#4      ResolverVisitor.visitBinaryExpression (package:analyzer/src/generated/resolver.dart:5547)
#5      BinaryExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:1218)
#6      SingleScopeResolver._resolveDartAstNode (package:angular_analyzer_plugin/src/resolver.dart:1175)
#7      SingleScopeResolver._resolveDartExpression (package:angular_analyzer_plugin/src/resolver.dart:1187)
#8      SingleScopeResolver.visitMustache (package:angular_analyzer_plugin/src/resolver.dart:935)
#9      Mustache.accept (package:angular_analyzer_plugin/ast.dart:181)
#10     AngularAstVisitor._visitAllChildren (package:angular_analyzer_plugin/ast.dart:38)
#11     AngularAstVisitor.visitTextInfo (package:angular_analyzer_plugin/ast.dart:31)
#12     TextInfo.accept (package:angular_analyzer_plugin/ast.dart:262)
#13     AngularScopeVisitor.visitElementInScope (package:angular_analyzer_plugin/src/resolver.dart:424)
#14     AngularScopeVisitor.visitElementInfo (package:angular_analyzer_plugin/src/resolver.dart:390)
#15     SingleScopeResolver.visitElementInfo (package:angular_analyzer_plugin/src/resolver.dart:923)
#16     ElementInfo.accept (package:angular_analyzer_plugin/ast.dart:309)
#17     AngularScopeVisitor.visitElementInScope (package:angular_analyzer_plugin/src/resolver.dart:424)
#18     AngularScopeVisitor.visitElementInfo (package:angular_analyzer_plugin/src/resolver.dart:390)
#19     SingleScopeResolver.visitElementInfo (package:angular_analyzer_plugin/src/resolver.dart:923)
#20     ElementInfo.accept (package:angular_analyzer_plugin/ast.dart:309)
#21     TemplateResolver._resolveScope (package:angular_analyzer_plugin/src/resolver.dart:300)
#22     TemplateResolver.resolve (package:angular_analyzer_plugin/src/resolver.dart:255)
#23     HtmlTemplateResolver.resolve (package:angular_analyzer_plugin/src/resolver.dart:191)
#24     ResolveHtmlTemplateTask.internalPerform (package:angular_analyzer_plugin/src/tasks.dart:1299)
#25     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#26     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#27     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#28     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#29     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#30     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#31     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#32     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:365)
#33     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:1007)
#34     Future.Future.<anonymous closure> (dart:async/future.dart:118)
```

**Comment by MichaelRFairhurst** [comment]
Merged #209
