### ISSUE TITLE
Analyzer crash when starting an anonymous function

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#205]
```
  {{()=>
```
and
```
  {{(){
```
both crash the analyzer server

stack trace:

```
 NoSuchMethodError: The setter 'returnType=' was called on null.        
Receiver: null                                                                   
Tried calling: returnType=Instance of 'DynamicTypeImpl'                          
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)              
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)               
#2      StaticTypeAnalyzer._inferLocalFunctionReturnType (package:analyzer/src/generated/static_type_analyzer.dart:2106)
#3      StaticTypeAnalyzer.visitFunctionExpression (package:analyzer/src/generated/static_type_analyzer.dart:481)
#4      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5330)
#5      ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6324)
#6      UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:2631)
#7      ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:7592)
#8      ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:6051)
#9      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5330)
#10     SingleScopeResolver._resolveDartAstNode (package:angular_analyzer_plugin/src/resolver.dart:1175)
#11     SingleScopeResolver._resolveDartExpression (package:angular_analyzer_plugin/src/resolver.dart:1187)
#12     SingleScopeResolver.visitMustache (package:angular_analyzer_plugin/src/resolver.dart:935)
#13     Mustache.accept (package:angular_analyzer_plugin/ast.dart:181)           
#14     AngularAstVisitor._visitAllChildren (package:angular_analyzer_plugin/ast.dart:38)
#15     AngularAstVisitor.visitTextInfo (package:angular_analyzer_plugin/ast.dart:31)
#16     TextInfo.accept (package:angular_analyzer_plugin/ast.dart:262)           
#17     AngularScopeVisitor.visitElementInScope (package:angular_analyzer_plugin/src/resolver.dart:424)
#18     AngularScopeVisitor.visitElementInfo (package:angular_analyzer_plugin/src/resolver.dart:390)
#19     SingleScopeResolver.visitElementInfo (package:angular_analyzer_plugin/src/resolver.dart:923)
#20     ElementInfo.accept (package:angular_analyzer_plugin/ast.dart:309)        
#21     AngularScopeVisitor.visitElementInScope (package:angular_analyzer_plugin/src/resolver.dart:424)
#22     AngularScopeVisitor.visitElementInfo (package:angular_analyzer_plugin/src/resolver.dart:390)
#23     SingleScopeResolver.visitElementInfo (package:angular_analyzer_plugin/src/resolver.dart:923)
#24     ElementInfo.accept (package:angular_analyzer_plugin/ast.dart:309)        
#25     TemplateResolver._resolveScope (package:angular_analyzer_plugin/src/resolver.dart:300)
#26     TemplateResolver.resolve (package:angular_analyzer_plugin/src/resolver.dart:255)
#27     HtmlTemplateResolver.resolve (package:angular_analyzer_plugin/src/resolver.dart:191)
#28     ResolveHtmlTemplateTask.internalPerform (package:angular_analyzer_plugin/src/tasks.dart:1299)
#29     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)       
#30     AnalysisTask.perform (package:analyzer/task/model.dart:220)              
#31     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#32     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#33     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#34     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#35     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#36     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:365)
#37     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:1007)
#38     Future.Future.<anonymous closure> (dart:async/future.dart:118)           
#39     _rootRun (dart:async/zone.dart:1146)                                     
```

**Comment by MichaelRFairhurst** [comment]
Looks like we need to run the equivalent of `_buildElements` from `deps/sdk/pkg/analyzer/lib/src/generated/incremental_resolver.dart` before resolving the tree, or we need to reject anonymous functions ahead of time

**Comment by MichaelRFairhurst** [comment]
#217 merged
