### ISSUE TITLE
Error getting dart when given special chars

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#206]
```
template: '\v'
```

causes a crash:

```
NoSuchMethodError: The getter 'start' was called on null.
Receiver: null
Tried calling: start
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      DartTemplateResolver._reportErrorForSpan (package:angular_analyzer_plugin/src/resolver.dart:99)
#3      DartTemplateResolver._addParseErrors (package:angular_analyzer_plugin/src/resolver.dart:91)
#4      DartTemplateResolver.resolve (package:angular_analyzer_plugin/src/resolver.dart:64)
#5      ResolveDartTemplatesTask.internalPerform (package:angular_analyzer_plugin/src/tasks.dart:1156)
#6      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#7      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#8      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#9      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#10     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#11     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#12     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#13     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:365)
#14     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:1007)
#15     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#16     _rootRun (dart:async/zone.dart:1146)
#17     _CustomZone.run (dart:async/zone.dart:1026)
#18     _CustomZone.runGuarded (dart:async/zone.dart:924)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
```

**Comment by MichaelRFairhurst** [comment]
@mk13 can you test that this error does/doesn't exist with angular_ast?
