### ISSUE TITLE
Cannot override a variable without a scope

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#210]
Repro:

```
{{x=y}}
```

This might only happen after using the branch from #209, I'm not sure.

```
Bad state: Cannot override without a scope
#0      TypeOverrideManager.setType (package:analyzer/src/generated/resolver.dart:8663)
#1      ResolverVisitor.overrideVariable (package:analyzer/src/generated/resolver.dart:5318)
#2      ResolverVisitor.overrideExpression (package:analyzer/src/generated/resolver.dart:5253)
#3      StaticTypeAnalyzer.visitAssignmentExpression (package:analyzer/src/generated/static_type_analyzer.dart:240)
#4      AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:913)
#5      ResolverVisitor.visitAssignmentExpression (package:analyzer/src/generated/resolver.dart:5476)
#6      AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:913)
#7      SingleScopeResolver._resolveDartAstNode (package:angular_analyzer_plugin/src/resolver.dart:1175)
#8      SingleScopeResolver._resolveDartExpression (package:angular_analyzer_plugin/src/resolver.dart:1187)
#9      SingleScopeResolver.visitMustache (package:angular_analyzer_plugin/src/resolver.dart:935)
#10     Mustache.accept (package:angular_analyzer_plugin/ast.dart:181)
#11     AngularAstVisitor._visitAllChildren (package:angular_analyzer_plugin/ast.dart:38)
#12     AngularAstVisitor.visitTextInfo (package:angular_analyzer_plugin/ast.dart:31)
#13     TextInfo.accept (package:angular_analyzer_plugin/ast.dart:262)
#14     AngularScopeVisitor.visitScopeRootElementWithTemplateAttribute (package:angular_analyzer_plugin/src/resolver.dart:412)
#15     AngularScopeVisitor.visitElementInfo (package:angular_analyzer_plugin/src/resolver.dart:381)
#16     SingleScopeResolver.visitElementInfo (package:angular_analyzer_plugin/src/resolver.dart:923)
#17     ElementInfo.accept (package:angular_analyzer_plugin/ast.dart:309)
#18     TemplateResolver._resolveScope (package:angular_analyzer_plugin/src/resolver.dart:300)
#19     TemplateResolver._resolveScope (package:angular_analyzer_plugin/src/resolver.dart:307)
#20     TemplateResolver.resolve (package:angular_analyzer_plugin/src/resolver.dart:255)
#21     HtmlTemplateResolver.resolve (package:angular_analyzer_plugin/src/resolver.dart:191)
#22     ResolveHtmlTemplateTask.internalPerform (package:angular_analyzer_plugin/src/tasks.dart:1299)
#23     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#24     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#25     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#26     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#27     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#28     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#29     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#30     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:365)
#31     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:1007)
#32     Future.Future.<anonymous closure> (dart:async/future.dart:118)
```

**Comment by MichaelRFairhurst** [comment]
Getting the same error when using 'as'
