### ISSUE TITLE
Star in front of # with no value causes "Operator ^ called on null"

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#213]
Repro:

```
  <div *#h1></div>
```

Stack trace:

```
NoSuchMethodError: The method '^' was called on null.
Receiver: null
Tried calling: ^(660693353)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      AnalysisError.hashCode (package:analyzer/error/error.dart:752)
#3      _HashSet._hashCode (dart:collection-patch/collection_patch.dart:564)
#4      _HashSet.add (dart:collection-patch/collection_patch.dart:600)
#5      RecordingErrorListener.onError (package:analyzer/error/listener.dart:310)
#6      PrepareScopeVisitor._defineLocalVariablesForAttributes (package:angular_analyzer_plugin/src/resolver.dart:623)
#7      PrepareScopeVisitor.visitScopeRootElementWithTemplateAttribute (package:angular_analyzer_plugin/src/resolver.dart:506)
#8      AngularScopeVisitor.visitElementInfo (package:angular_analyzer_plugin/src/resolver.dart:381)
#9      ElementInfo.accept (package:angular_analyzer_plugin/ast.dart:309)
#10     TemplateResolver._resolveScope (package:angular_analyzer_plugin/src/resolver.dart:282)
#11     TemplateResolver._resolveScope (package:angular_analyzer_plugin/src/resolver.dart:307)
#12     TemplateResolver.resolve (package:angular_analyzer_plugin/src/resolver.dart:255)
#13     HtmlTemplateResolver.resolve (package:angular_analyzer_plugin/src/resolver.dart:191)
#14     ResolveHtmlTemplateTask.internalPerform (package:angular_analyzer_plugin/src/tasks.dart:1299)
#15     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#16     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#17     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#18     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#19     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#20     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#21     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#22     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:365)
#23     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:1007)
#24     Future.Future.<anonymous closure> (dart:async/future.dart:118)
```

**Comment by MichaelRFairhurst** [comment]
Merged #216
