### ISSUE TITLE
Analyzer server crashing with Receiver: null error 

### ISSUE THREAD

**Issue by sureshg** [dart-lang/angular_analyzer_plugin#222]
Followed the instructions and built new server snapshot, but the analysis server is failing with `Receiver: null` error for a simple dart application - https://github.com/sureshg/inactivity-ng2dart/blob/master/lib/app_component.dart. I couldn't figure it out much from the error message, so reporting here.

Analyzer Feedback from IntelliJ

## Version information

- `IDEA 171.2014.24`
- `1.22.0-dev.6.0`
- `WS-171.2014.24, JRE 1.8.0_112-release-b621x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12 unknown, screens 1440x900  Retina`

## Exception

```
Dart analysis server, SDK version 1.22.0-dev.6.0, server version 1.17.0, error: Analysis failed: /Users/sgopal1/code/dart/inactivity/lib/app_component.dart
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      InputPackagesResultProvider.hasResultsForSource (package:analyzer/src/summary/package_bundle_reader.dart:36)
#3      ResynthesizerResultProvider.compute (package:analyzer/src/summary/package_bundle_reader.dart:181)
#4      AnalysisContextImpl.aboutToComputeResult.<anonymous closure> (package:analyzer/src/context/context.dart:573)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.aboutToComputeResult (package:analyzer/src/context/context.dart:571)
#7      WorkItem.gatherInputs (package:analyzer/src/task/driver.dart:746)
#8      _WorkOrderDependencyWalker.getNextInput (package:analyzer/src/task/driver.dart:879)
#9      CycleAwareDependencyWalker.getNextStronglyConnectedComponent (package:analyzer/src/task/driver.dart:414)
#10     WorkOrder.moveNext.<anonymous closure> (package:analyzer/src/task/driver.dart:845)
#11     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#12     WorkOrder.moveNext (package:analyzer/src/task/driver.dart:837)
#13     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:108)
#14     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:723)
#15     AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:665)
#16     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:693)
#17     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1484)
#18     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:679)
#19     AnalysisDriver._performWork.<_performWork_async_body> (package:analyzer/src/dart/analysis/driver.dart:1038)
#20     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#21     _rootRun (dart:async/zone.dart:1146)
#22     _CustomZone.run (dart:async/zone.dart:1026)
#23     _CustomZone.runGuarded (dart:async/zone.dart:924)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#25     _rootRun (dart:async/zone.dart:1150)
#26     _CustomZone.run (dart:async/zone.dart:1026)
#27     _CustomZone.runGuarded (dart:async/zone.dart:924)
#28     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

```

```
1484034767259 <= {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /Users/sgopal1/code/dart/inactivity/lib/app_component.dart","stackTrace":"NoSuchMethodError: The getter '
1484034753645 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
1484034753641 <= {"id":"5"}
1484034753637 <= {"id":"4"}
1484034753634 <= {"id":"3"}
1484034753117 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1484034753110 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1484034753072 <= {"id":"2"}
1484034753066 <= {"id":"1"}
1484034753062 => {"id":"5","method":"analysis.setSubscriptions","params":{"subscriptions":{"HIGHLIGHTS":["/Users/sgopal1/code/dart/inactivity/lib/app_component.html"],"OVERRIDES":["/Users/sgopal1/code
1484034753062 => {"id":"4","method":"analysis.setPriorityFiles","params":{"files":["/Users/sgopal1/code/dart/inactivity/lib/app_component.html"]},"clientRequestTime":1484034752046}
1484034753062 => {"id":"3","method":"analysis.setAnalysisRoots","params":{"included":["/Users/sgopal1/code/dart/inactivity"],"excluded":["/Users/sgopal1/code/dart/inactivity/.idea","/Users/sgopal1/cod
1484034753061 => {"id":"2","method":"analysis.updateOptions","params":{"options":{"enableAsync":true,"enableDeferredLoading":true,"enableEnums":true,"enableNullAwareOperators":true,"enableSuperMixins"
1484034753061 => {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1484034752036}
1484034753059 <= {"id":"0","result":{"version":"1.17.0"}}
1484034752983 <= {"event":"server.error","params":{"isFatal":false,"message":"Exception from analysis domain receiver: (AnalysisDomain) => void","stackTrace":"Bad state: Should not be used with the ne
1484034752950 <= {"event":"server.connected","params":{"version":"1.17.0","pid":14259,"sessionId":""}}
  /usr/local/opt/dart/libexec/bin/dart /usr/local/opt/dart/libexec/bin/snapshots/analysis_server.dart.snapshot --client-id=WebStorm --client-version=WS-171.2014.24 --useAnalysisHighlight2
1484034751949 started analysis server:
```

```
Dart analysis server, SDK version 1.22.0-dev.6.0, server version 1.17.0, error: Analysis failed: /Users/sgopal1/code/dart/inactivity/lib/app_component.dart
NoSuchMethodError: The getter 'uri' was called on null.
Receiver: null
Tried calling: uri
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      InputPackagesResultProvider.hasResultsForSource (package:analyzer/src/summary/package_bundle_reader.dart:36)
#3      ResynthesizerResultProvider.compute (package:analyzer/src/summary/package_bundle_reader.dart:181)
#4      AnalysisContextImpl.aboutToComputeResult.<anonymous closure> (package:analyzer/src/context/context.dart:573)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.aboutToComputeResult (package:analyzer/src/context/context.dart:571)
#7      WorkItem.gatherInputs (package:analyzer/src/task/driver.dart:746)
#8      _WorkOrderDependencyWalker.getNextInput (package:analyzer/src/task/driver.dart:879)
#9      CycleAwareDependencyWalker.getNextStronglyConnectedComponent (package:analyzer/src/task/driver.dart:414)
#10     WorkOrder.moveNext.<anonymous closure> (package:analyzer/src/task/driver.dart:845)
#11     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#12     WorkOrder.moveNext (package:analyzer/src/task/driver.dart:837)
#13     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:108)
#14     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:723)
#15     AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:665)
#16     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:693)
#17     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1484)
#18     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:679)
#19     AnalysisDriver._performWork.<_performWork_async_body> (package:analyzer/src/dart/analysis/driver.dart:1038)
#20     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#21     _rootRun (dart:async/zone.dart:1146)
#22     _CustomZone.run (dart:async/zone.dart:1026)
#23     _CustomZone.runGuarded (dart:async/zone.dart:924)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#25     _rootRun (dart:async/zone.dart:1150)
#26     _CustomZone.run (dart:async/zone.dart:1026)
#27     _CustomZone.runGuarded (dart:async/zone.dart:924)
#28     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)

**Comment by zoechi** [comment]
Could be dart-lang/sdk#28265

**Comment by MichaelRFairhurst** [comment]
Shoot. We are working on this.

You can try to rebuild against an older SDK by running:

```
cd deps/sdk
git checkout 1.22.0-dev.4.0
```

and then running `bin/make_snapshot`.

Its possible a transitive dependency will break, but with any luck that will get your analysis running successfully.

**Comment by MichaelRFairhurst** [comment]
Closing this -- the master branch works with the latest SDK. Thanks for reporting, glad to be back up and running :)

**Comment by sureshg** [comment]
@MichaelRFairhurst thanks..it's working now even though the angular template analysis has some issues :)  Eg: 
<img width="657" alt="screen shot 2017-05-01 at 1 49 39 pm" src="https://cloud.githubusercontent.com/assets/356994/25594370/0d19a084-2e75-11e7-9ddf-cbced48fdb68.png">

**Comment by MichaelRFairhurst** [comment]
Glad you're giving it a try!

This is an issue with pub transformers! Unfortunately we still don't support them just yet :( If you add `NgFor` to the `directives` list, this should no longer complain.
