### ISSUE TITLE
building the plugin causes errors

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#238]
```
(master) $ ~/scripts/update_angular_analyzler_plugin.sh 
Von https://github.com/dart-lang/angular_analyzer_plugin
 * branch            master     -> FETCH_HEAD
Bereits aktuell.
Using depot tools to pull in the SDK
Syncing projects: 100% (87/87), done.                                     

________ running 'download_from_google_storage --no_auth --no_resume --quiet --platform=linux* --bucket chromium-gn -s sdk/buildtools/linux64/gn.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'

________ running 'download_from_google_storage --no_auth --no_resume --quiet --platform=darwin --bucket chromium-gn -s sdk/buildtools/mac/gn.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'

________ running 'download_from_google_storage --no_auth --no_resume --quiet --platform=win* --bucket chromium-gn -s sdk/buildtools/win/gn.exe.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'

________ running 'download_from_google_storage --no_auth --no_resume --quiet --platform=win32 --bucket chromium-clang-format -s sdk/buildtools/win/clang-format.exe.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'

________ running 'download_from_google_storage --no_auth --no_resume --quiet --platform=linux* --bucket chromium-clang-format -s sdk/buildtools/linux64/clang-format.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'

________ running 'download_from_google_storage --no_auth --no_resume --quiet --platform=darwin --bucket chromium-clang-format -s sdk/buildtools/mac/clang-format.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'

________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --recursive --directory sdk/third_party/d8' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
0> File sdk/third_party/d8/linux/d8 exists and SHA1 matches. Skipping.
0> File sdk/third_party/d8/linux/d8-arm exists and SHA1 matches. Skipping.
0> File sdk/third_party/d8/windows/d8.exe exists and SHA1 matches. Skipping.
0> File sdk/third_party/d8/macos/d8 exists and SHA1 matches. Skipping.
Success!
Downloading 4 files took 0.077856 second(s)

________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --recursive --auto_platform --extract --directory sdk/tools/sdks' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
0> File sdk/tools/sdks/linux/dart-sdk.tar.gz exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.039516 second(s)

________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --recursive --auto_platform --extract --directory sdk/third_party/firefox_jsshell' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
0> File sdk/third_party/firefox_jsshell/linux/jsshell.tar.gz exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.011442 second(s)

________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --platform=win32 --directory sdk/third_party/drt_resources' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
The current platform doesn't match "win32", skipping.

________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --extract -s sdk/third_party/pkg/unittest.tar.gz.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
0> File sdk/third_party/pkg/unittest.tar.gz exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.001249 second(s)

________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --platform=win32 --extract -s sdk/third_party/7zip.tar.gz.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
The current platform doesn't match "win32", skipping.

________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --extract -s sdk/third_party/gsutil.tar.gz.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
0> File sdk/third_party/gsutil.tar.gz exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.007335 second(s)

________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --platform=linux* --extract -s sdk/third_party/clang.tar.gz.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
0> File sdk/third_party/clang.tar.gz exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.040053 second(s)

________ running '/usr/bin/python sdk/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook --arch i386' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
Debian Wheezy i386 root image already up-to-date: /home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/build/linux/debian_wheezy_i386-sysroot

________ running '/usr/bin/python sdk/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook --arch amd64' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
Debian Wheezy amd64 root image already up-to-date: /home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/build/linux/debian_wheezy_amd64-sysroot

________ running '/usr/bin/python sdk/tools/clang/scripts/update.py --if-needed' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
Updating Clang to 282487-1...
Clang is already up to date.

________ running '/usr/bin/python sdk/build/vs_toolchain.py update' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'

________ running '/usr/bin/python sdk/tools/generate_buildfiles.py' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
Command failed: /home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/buildtools/linux64/gn gen --check out/DebugIA32 --args=is_release=false is_clang=false dart_zlib_path="//runtime/bin/zlib" use_goma=false dart_use_fallback_root_certificates=true target_cpu="x86" goma_dir="None" dart_use_tcmalloc=true dart_target_arch="ia32" is_asan=false is_product=false is_debug=true dart_runtime_mode="develop" dart_host_pub_exe="" dart_debug=true is_msan=false host_cpu="x86" is_tsan=false target_os="linux"
output: ERROR at //build/prebuilt_dart_sdk.gni:12:28: Script returned non-zero exit code.
_prebuilt_dart_exe_trial = exec_script("gn_run_binary.py",
                           ^----------
Current dir: /home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/out/DebugIA32/
Command: python -- /home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/build/gn_run_binary.py exec_script /home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/tools/sdks/linux/dart-sdk/bin/dart --version
Returned 1.
stderr:

Traceback (most recent call last):
  File "/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/build/gn_run_binary.py", line 61, in <module>
    sys.exit(main(sys.argv))
  File "/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/build/gn_run_binary.py", line 54, in main
    result = run_command(args)
  File "/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/build/gn_run_binary.py", line 24, in run_command
    subprocess.check_output(command, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

See //runtime/vm/BUILD.gn:6:1: whence it was imported.
import("../../build/prebuilt_dart_sdk.gni")
^-----------------------------------------
See //BUILD.gn:44:5: which caused the file to be included.
    "runtime/vm:patched_sdk",
    ^-----------------------
Error: Command '/usr/bin/python sdk/tools/generate_buildfiles.py' returned non-zero exit status 1 in /home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps
done
Updating pub deps
Resolving dependencies... 
Got dependencies!
done

Updating the sdk with depot_tools
Syncing projects: 100% (87/87), done.                                     

________ running 'download_from_google_storage --no_auth --no_resume --quiet --platform=linux* --bucket chromium-gn -s sdk/buildtools/linux64/gn.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'

________ running 'download_from_google_storage --no_auth --no_resume --quiet --platform=darwin --bucket chromium-gn -s sdk/buildtools/mac/gn.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'

________ running 'download_from_google_storage --no_auth --no_resume --quiet --platform=win* --bucket chromium-gn -s sdk/buildtools/win/gn.exe.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'

________ running 'download_from_google_storage --no_auth --no_resume --quiet --platform=win32 --bucket chromium-clang-format -s sdk/buildtools/win/clang-format.exe.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'

________ running 'download_from_google_storage --no_auth --no_resume --quiet --platform=linux* --bucket chromium-clang-format -s sdk/buildtools/linux64/clang-format.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'

________ running 'download_from_google_storage --no_auth --no_resume --quiet --platform=darwin --bucket chromium-clang-format -s sdk/buildtools/mac/clang-format.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'

________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --recursive --directory sdk/third_party/d8' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
0> File sdk/third_party/d8/linux/d8 exists and SHA1 matches. Skipping.
0> File sdk/third_party/d8/linux/d8-arm exists and SHA1 matches. Skipping.
0> File sdk/third_party/d8/windows/d8.exe exists and SHA1 matches. Skipping.
0> File sdk/third_party/d8/macos/d8 exists and SHA1 matches. Skipping.
Success!
Downloading 4 files took 0.077787 second(s)

________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --recursive --auto_platform --extract --directory sdk/tools/sdks' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
0> File sdk/tools/sdks/linux/dart-sdk.tar.gz exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.039868 second(s)

________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --recursive --auto_platform --extract --directory sdk/third_party/firefox_jsshell' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
0> File sdk/third_party/firefox_jsshell/linux/jsshell.tar.gz exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.011310 second(s)

________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --platform=win32 --directory sdk/third_party/drt_resources' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
The current platform doesn't match "win32", skipping.

________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --extract -s sdk/third_party/pkg/unittest.tar.gz.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
0> File sdk/third_party/pkg/unittest.tar.gz exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.001063 second(s)

________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --platform=win32 --extract -s sdk/third_party/7zip.tar.gz.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
The current platform doesn't match "win32", skipping.

________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --extract -s sdk/third_party/gsutil.tar.gz.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
0> File sdk/third_party/gsutil.tar.gz exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.006807 second(s)

________ running 'download_from_google_storage --no_auth --no_resume --bucket dart-dependencies --platform=linux* --extract -s sdk/third_party/clang.tar.gz.sha1' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
0> File sdk/third_party/clang.tar.gz exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.042765 second(s)

________ running '/usr/bin/python sdk/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook --arch i386' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
Debian Wheezy i386 root image already up-to-date: /home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/build/linux/debian_wheezy_i386-sysroot

________ running '/usr/bin/python sdk/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook --arch amd64' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
Debian Wheezy amd64 root image already up-to-date: /home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/build/linux/debian_wheezy_amd64-sysroot

________ running '/usr/bin/python sdk/tools/clang/scripts/update.py --if-needed' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
Updating Clang to 282487-1...
Clang is already up to date.

________ running '/usr/bin/python sdk/build/vs_toolchain.py update' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'

________ running '/usr/bin/python sdk/tools/generate_buildfiles.py' in '/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps'
Command failed: /home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/buildtools/linux64/gn gen --check out/DebugIA32 --args=is_release=false is_clang=false dart_zlib_path="//runtime/bin/zlib" use_goma=false dart_use_fallback_root_certificates=true target_cpu="x86" goma_dir="None" dart_use_tcmalloc=true dart_target_arch="ia32" is_asan=false is_product=false is_debug=true dart_runtime_mode="develop" dart_host_pub_exe="" dart_debug=true is_msan=false host_cpu="x86" is_tsan=false target_os="linux"
output: ERROR at //build/prebuilt_dart_sdk.gni:12:28: Script returned non-zero exit code.
_prebuilt_dart_exe_trial = exec_script("gn_run_binary.py",
                           ^----------
Current dir: /home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/out/DebugIA32/
Command: python -- /home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/build/gn_run_binary.py exec_script /home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/tools/sdks/linux/dart-sdk/bin/dart --version
Returned 1.
stderr:

Traceback (most recent call last):
  File "/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/build/gn_run_binary.py", line 61, in <module>
    sys.exit(main(sys.argv))
  File "/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/build/gn_run_binary.py", line 54, in main
    result = run_command(args)
  File "/home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps/sdk/build/gn_run_binary.py", line 24, in run_command
    subprocess.check_output(command, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

See //runtime/vm/BUILD.gn:6:1: whence it was imported.
import("../../build/prebuilt_dart_sdk.gni")
^-----------------------------------------
See //BUILD.gn:44:5: which caused the file to be included.
    "runtime/vm:patched_sdk",
    ^-----------------------
Error: Command '/usr/bin/python sdk/tools/generate_buildfiles.py' returned non-zero exit status 1 in /home/zoechi/dart/dart-lang/angular_analyzer_plugin/deps
done

Copying and transforming sdk .packages to be useful to this repo
done

Copying pub .packages to be useful to this repo
done

Adding analyzer plugin to .packages
done

Adding server to .packages
done
```
the resulting snapshot seems to work though

> Dart VM version: 1.22.0-edge.7730809f360a00d9683057ffcfb9651453e7c1f4 (Sat Jan 21 00:04:30 2017) on "linux_x64"

**Comment by MichaelRFairhurst** [comment]
We will be doing heavy refactoring to get the analyzer to work with this plugin since they changed to use summaries. I should add a note to the readme that it is currently very broken.
