### ISSUE TITLE
Lots of "The getter 'fullName' was called on null." 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#269]
```
2017-04-10 14:06:40,770 [11852170]   WARN - yzer.DartAnalysisServerService - Dart analysis server, SDK version 1.24.0-edge.1ec54ff2df89fcd7238ed650fe1c26d0c082055e, server version 1.18.0, error: Captured exception
NoSuchMethodError: The getter 'fullName' was called on null.
Receiver: null
Tried calling: fullName
#0      Driver._captureExceptions.<anonymous closure> (package:analysis_server/src/server/driver.dart:517)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:981)
#2      _Future._propagateToListeners (dart:async/future_impl.dart:552)
#3      _Future._completeError (dart:async/future_impl.dart:486)
#4      _completeWithErrorCallback (dart:async/future.dart:846)
#5      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:186)
#6      _rootRun (dart:async/zone.dart:1116)
#7      _CustomZone.run (dart:async/zone.dart:1001)
#8      _CustomZone.runGuarded (dart:async/zone.dart:901)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#10     _rootRun (dart:async/zone.dart:1120)
#11     _CustomZone.run (dart:async/zone.dart:1001)
#12     _CustomZone.runGuarded (dart:async/zone.dart:901)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#16     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:375)
#17     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
<asynchronous suspension>
#19     AngularDriver.performWork (package:angular_analyzer_plugin/src/angular_driver.dart:153)
<asynchronous suspension>
#20     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1403)
<asynchronous suspension>
#21     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1337)
#22     AnalysisServer.AnalysisServer (package:analysis_server/src/analysis_server.dart:421)
#23     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:95)
#24     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)
#25     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:489)
#26     _rootRun (dart:async/zone.dart:1120)
#27     _CustomZone.run (dart:async/zone.dart:1001)
#28     runZoned (dart:async/zone.dart:1465)
#29     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:528)
#30     Driver.start (package:analysis_server/src/server/driver.dart:488)
#31     main (file:///home/zoechi/dart/dart-lang/angular_analyzer_plugin/server_plugin/bin/server.dart:21)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

> Dart VM version: 1.24.0-edge.1ec54ff2df89fcd7238ed650fe1c26d0c082055e (Sun Apr  2 22:58:41 2017) on "linux_x64"

**Comment by scheglov** [comment]
Most probably this is the result of https://github.com/dart-lang/sdk/commit/021d99e05deae069352f5b8d2c00f1ef0b1f00f3.
Do you know how I could reproduce this?

**Comment by zoechi** [comment]
I installed the plugin and run the analyzer on an existing project.
I didn't get any other feedback :-/

**Comment by scheglov** [comment]
Do you have any `exception*` files in `~/.dartServer/.analysis-driver`?

**Comment by zoechi** [comment]
I wasn't able to reproduce today. 
I'll investigate further and update when I find out more.

**Comment by zoechi** [comment]
This is the issue I'm currently struggling with dart-lang/sdk#29322

**Comment by MichaelRFairhurst** [comment]
the dart lang ticket is closed, so I'll close this, but please reopen if it isn't indeed fixed (in both places!)
