### ISSUE TITLE
Exception from navigation contributor: AngularNavigationContributor

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/angular_analyzer_plugin#308]
Here's a partial stack trace:

```
NoSuchMethodError: The getter 'offset' was called on null. Receiver: null Tried calling: offset

#0 Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1 Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2 AngularNavigationContributor._addDirectiveRegions (package:angular_analyzer_server_plugin/src/analysis.dart:94)
#3 AngularNavigationContributor.computeNavigation (package:angular_analyzer_server_plugin/src/analysis.dart:54)
#4 computeNavigation (packa...
```

**Comment by MichaelRFairhurst** [comment]
This was solved a few months ago. I need to go to these peoples' desks to make them update under armed oversight I think. :)

https://github.com/dart-lang/angular_analyzer_plugin/pull/187#pullrequestreview-14511968

**Comment by devoncarew** [comment]
Ah, ok! Consider this a time capsule from the past then :)
