### ISSUE TITLE
Completion request - AbortCompletion issue

### ISSUE THREAD

**Issue by mk13** [dart-lang/angular_analyzer_plugin#326]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-171.4249.39`
- `1.24.0-dev.4.0`
- `IU-171.4249.39, JRE 1.8.0_112-release-736-b16x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.4 unknown, screens 1440x900, 1200x1920  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/83/h011zfcd1x3d5nshw8mb8wj000d2hp/T/report1.txt

```
Dart analysis server, SDK version 1.24.0-dev.4.0, server version 1.18.0, error: Failed to handle completion domain request: {id: 1752, method: completion.getSuggestions, params: {file: /Users/maxkim/Documents/angular2_quickstart/lib/app_component.html, offset: 324}, clientRequestTime: 1494958390862}
Instance of 'AbortCompletion'
#0      CompletionRequestImpl.checkAborted (package:analysis_server/src/services/completion/completion_core.dart:78)
#1      new EmbeddedDartCompletionRequest.from (package:angular_analyzer_server_plugin/src/embedded_dart_completion_request.dart:17)
#2      TemplateCompleter.computeSuggestions (package:angular_analyzer_server_plugin/src/completion.dart:303)
<asynchronous suspension>
#3      AngularCompletionContributor.computeSuggestions (package:angular_analyzer_server_plugin/src/completion.dart:269)
<asynchronous suspension>
#4      Starter.sendAngularCompletions (package:angular_analyzer_plugin/starter.dart:114)
<asynchronous suspension>
#5      CompletionDomainHandler.processRequest (package:analysis_server/src/domain_completion.dart:170)
<asynchronous suspension>
#6      CompletionDomainHandler.handleRequest.<anonymous closure> (package:analysis_server/src/domain_completion.dart:137)
#7      _rootRun (dart:async/zone.dart:1120)
#8      _CustomZone.run (dart:async/zone.dart:1001)
#9      _CustomZone.runGuarded (dart:async/zone.dart:901)
#10     runZoned (dart:async/zone.dart:1465)

**Comment by MichaelRFairhurst** [comment]
Haven't seen this in forever
