### ISSUE TITLE
exception during autocomplete

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#449]
"message": "RangeError: Value not in range: 1",
          "stackTrace": "#0      _StringBase.substring (dart:core-patch/string_patch.dart:365)\n#1      TemplateCompleter._createInputInTemplateSuggestion (package:angular_analyzer_plugin/src/completion.dart:1121:37)\n#2      TemplateCompleter.suggestInputsInTemplate (package:angular_analyzer_plugin/src/completion.dart:866:33)\n#3      TemplateCompleter.computeSuggestions (package:angular_analyzer_plugin/src/completion.dart:687:7)\n\u003casynchronous suspension\u003e\n#4      AngularCompletionContributor.computeSuggestions (package:angular_analyzer_plugin/src/completion.dart:553:31)\n\u003casynchronous suspension\u003e\n#5      CompletionGenerator.generateCompletionResponse (package:analyzer_plugin/utilities/completion/completion_core.dart:108:29)\n\u003casynchronous suspension\u003e\n#6      ServerPlugin\u0026CompletionMixin.handleCompletionGetSuggestions (package:analyzer_plugin/plugin/completion_mixin.dart:47:25)\n\u003casynchronous suspension\u003e\n#7      ServerPlugin._getResponse (package:analyzer_plugin/plugin/plugin.dart:620:24)\n\u003casynchronous suspension\u003e\n#8      ServerPlugin._onRequest (package:analyzer_plugin/plugin/plugin.dart:670:24)\n\u003casynchronous suspension\u003e\n#9      PluginIsolateChannel.listen.onData (package:analyzer_plugin/src/channel/isolate_channel.dart:127:18)\n#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314)\n#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)\n#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)\n#13     _StreamController\u0026\u0026_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:770)\n#14     _StreamController._add (dart:async/stream_controller.dart:641)\n#15     _StreamController.add (dart:async/stream_controller.dart:587)\n#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)\n",

**Comment by MichaelRFairhurst** [comment]
Solved in #475
