### ISSUE TITLE
accept called on null

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#500]
NoSuchMethodError: The method 'accept' was called on null.\nReceiver: null\nTried calling: accept(Instance of '_LocalBestTypeVisitor')",
          "stackTrace": "#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)\n#1      LocalDeclarationVisitor.visitNode (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:189:17)\n#2      GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494:39)\n#3      GeneralizingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:291:59)\n#4      ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4227:49)\n#5      LocalDeclarationVisitor.visitNode (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:189:17)\n#6      GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:284:41)\n#7      GeneralizingAstVisitor.visitAssignmentExpression (package:analyzer/dart/ast/visitor.dart:175:7)\n#8      AssignmentExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:906:49)\n#9      LocalDeclarationVisitor.visitNode (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:189:17)\n#10     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:284:41)\n#11     GeneralizingAstVisitor.visitIdentifier (package:analyzer/dart/ast/visitor.dart:348:41)\n#12     GeneralizingAstVisitor.visitPrefixedIdentifier (package:analyzer/dart/ast/visitor.dart:455:57)\n#13     PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8737:49)\n#14     LocalDeclarationVisitor.visitNode (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:189:17)\n#15     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:284:41)\n#16     GeneralizingAstVisitor.visitIdentifier (package:analyzer/dart/ast/visitor.dart:348:41)\n#17     GeneralizingAstVisitor.visitSimpleIdentifier (package:analyzer/dart/ast/visitor.dart:485:53)\n#18     SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9413:49)\n#19     LocalDeclarationVisitor.visit (package:analyzer_plugin/src/utilities/visitors/local_declaration_visitor.dart:64:12)\n#20     TypeMemberContributor._computeSuggestions (package:analyzer_plugin/utilities/completion/type_member_contributor.dart:137:23)\n#21     TypeMemberContributor.computeSuggestionsWithEntryPoint (package:analyzer_plugin/utilities/completion/type_member_contributor.dart:66:5)\n\u003casynchronous suspension\u003e\n#22     NgTypeMemberContributor.computeSuggestions (package:angular_analyzer_plugin/src/completion.dart:234:38)\n\u003casynchronous suspension\u003e\n#23     CompletionGenerator.generateCompletionResponse (package:analyzer_plugin/utilities/completion/completion_core.dart:108:29)\n\u003casynchronous suspension\u003e\n#24     ServerPlugin\u0026CompletionMixin.handleCompletionGetSuggestions (package:analyzer_plugin/plugin/completion_mixin.dart:47:25)\n\u003casynchronous suspension\u003e\n#25     ServerPlugin._getResponse (package:analyzer_plugin/plugin/plugin.dart:620:24)\n\u003casynchronous suspension\u003e\n#26     ServerPlugin._onRequest (package:analyzer_plugin/plugin/plugin.dart:670:24)\n\u003casynchronous suspension\u003e\n#27     PluginIsolateChannel.listen.onData (package:analyzer_plugin/src/channel/isolate_channel.dart:127:18)\n#28     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)\n#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)\n#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)\n#31     _StreamController\u0026\u0026_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:762)\n#32     _StreamController._add (dart:async/stream_controller.dart:638)\n#33     _StreamController.add (dart:async/stream_controller.dart:584)\n#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)\n

**Comment by MichaelRFairhurst** [comment]
Fixed in the SDK, but requires a republish of pkg:plugin
