### ISSUE TITLE
Analysis plugin not starting

### ISSUE THREAD

**Issue by MderM** [dart-lang/angular_analyzer_plugin#582]
On Windows.

Clean installed DartSDK & IntelliJ + Dart plugin.

Created a new project from the given dart template with using the angular components library (the todo list thing).

Analyzer doesn't do anything. No errors, warnings or autocomplete help on Angular directives, tags or attributes. IntelliJ states all of this just as 'unknown html tag' or 'attribute *ngwhatever' is not allowed here. Also no navigation.

Looking into the diagnostics page on plugins section it states:

Analysis plugins

angular-5.0.0-alpha+15

bootstrap package path: C:\Users\mmewes\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\angular-5.0.0-alpha+15\tools\analyzer_plugin

execution path: C:\Users\mmewes\AppData\Local\.dartServer\.plugin_manager\efa1f21418784423f0133487011da639\analyzer_plugin\bin\plugin.dart

packages file path: C:\Users\mmewes\AppData\Local\.dartServer\.plugin_manager\efa1f21418784423f0133487011da639\analyzer_plugin\.packages

not running

with following output:
```
IsolateSpawnException: Unable to spawn isolate: file:///C:/Users/mmewes/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/angular_analyzer_plugin-0.0.15+1/lib/src/converter.dart:284:16: Error: A value of type '(#lib1::ParsedEventAst) → #lib2::StatementsBoundAttribute' can't be assigned to a variable of type '(#lib1::EventAst) → dynamic'.
Try changing the type of the left hand side, or casting the right hand side to '(#lib1::EventAst) → dynamic'.
    events.map(_convertStatementsBoundAttribute).forEach(returnAttributes.add);
               ^
#0      Isolate.spawnUri (dart:isolate/runtime/libisolate_patch.dart:450:14)

#1      DiscoveredServerIsolateChannel._spawnIsolate (package:analyzer_plugin/src/channel/isolate_channel.dart:76:20)
#2      ServerIsolateChannel.listen (package:analyzer_plugin/src/channel/isolate_channel.dart:251:24)

#3      PluginSession.start (package:analysis_server/src/plugin/plugin_manager.dart:1074:19)

#4      PluginInfo.start (package:analysis_server/src/plugin/plugin_manager.dart:255:43)

#5      PluginManager.addPluginToContextRoot (package:analysis_server/src/plugin/plugin_manager.dart:403:48)

#6      PluginWatcher.addedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:78:19)
#7      AnalysisDriverScheduler.add (package:analyzer/src/dart/analysis/driver.dart:1912:22)
#8      new AnalysisDriver (package:analyzer/src/dart/analysis/driver.dart:369:16)
#9      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:194:33)
#10     ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:1227:48)
#11     ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1139:19)
#12     ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1179:16)
#13     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:757:9)
#14     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:918:22)
#15     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:348:12)
#16     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:273:16)
#17     AnalysisServer.handleRequest.. (package:analysis_server/src/analysis_server.dart:746:45)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#19     AnalysisServer.handleRequest. (package:analysis_server/src/analysis_server.dart:742:50)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _runZoned (dart:async/zone.dart:1518:10)
#23     runZoned (dart:async/zone.dart:1502:12)
#24     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:741:5)
#25     ByteStreamServerChannel._readRequest. (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#26     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210:15)
#27     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#28     ByteStreamServerChannel.listen. (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#29     _rootRunUnary (dart:async/zone.dart:1134:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#36     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#37     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#38     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#39     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#40     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#41     _rootRunUnary (dart:async/zone.dart:1134:38)
#42     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#46     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#47     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#48     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#49     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#50     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#51     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#52     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#53     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#54     _rootRunUnary (dart:async/zone.dart:1134:38)
#55     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#59     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#60     _StreamController._add (dart:async/stream_controller.dart:639:7)
#61     _StreamController.add (dart:async/stream_controller.dart:585:5)
#62     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1672:41)
#63     _rootRunUnary (dart:async/zone.dart:1138:13)
#64     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#65     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#66     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#67     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#68     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#69     _StreamController._add (dart:async/stream_controller.dart:639:7)
#70     _StreamController.add (dart:async/stream_controller.dart:585:5)
#71     new _RawSocket. (dart:io/runtime/binsocket_patch.dart:1245:33)
#72     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:797:14)
#73     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#74     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#75     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#76     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)
```

Any help is welcome... are there any secret swithes I can turn off/on?

**Comment by MderM** [comment]
To add more information.

I tried on three machines, where two of them were my main development boxes (windows 10) cluttered with development stuff of different frameworks and languages.

To be sure that this is not an interference with flutter, I tried a clean install of SDK & IntelliJ on a Windows Server 2012 machine.

Always with the same outcome.

**Comment by devoncarew** [comment]
@MichaelRFairhurst, the above exception looks like the angular plugin - or at least version `0.0.15+1` - is not strong mode at runtime clean. People will likely be getting hit by this now that preview dart 2 is enabled by the VM by default.

**Comment by MichaelRFairhurst** [comment]
Thanks for filing @MderM!

We have dart 2 support in "unpublished changes" still. I just opened #583 to get those out! Once that lands, I will close this ticket & give upgrade instructions.

**Comment by cooler-king** [comment]
Hitting this too.  Windows 10.  SDK 2.0.0-dev.66.0.  angular 5.0.0-beta.

When can we expect 0.0.16 to be published?

**Comment by MichaelRFairhurst** [comment]
I made a procedural mistake in getting this out (two PRs to fix travis instead of one, so both looked broken). Hopefully can get this fixed for real soon. Apologies for the delays here everybody!

**Comment by MichaelRFairhurst** [comment]
OK, this is finally published.

Please let me know if you have any issues -- you should be able to just restart your analysis server or IDE and get the latest working version.

**Comment by rbishop-bah** [comment]
With 0.0.16 activated and Dart 2.0.0-dev.67.0 the analyzer crashes early:

![image](https://user-images.githubusercontent.com/3227777/42253398-9c7e0e04-7f0f-11e8-9810-16d2392e48bb.png)

**Comment by devoncarew** [comment]
@rbishop-bah, thanks for the report! This looks like a strong-mode-at-runtime issue; while we investigate, you can unblock yourself by switching back to an `2.0.0-dev.63.0` or earlier sdk - before we switched the `--preview-dart-2` default for Dart sdks.

**Comment by devoncarew** [comment]
I'm going to close this issue - which was a separate crash - and track the remaining startup issue here: https://github.com/dart-lang/sdk/issues/33808.
