### ISSUE TITLE
Plugin not working at all 2.1.0-dev.9.4

### ISSUE THREAD

**Issue by Gee5ive** [dart-lang/angular_analyzer_plugin#663]
Hi, I'm using macOS Mojave , Intellj 2018.2.5 ultimate  , Dart SDK 2.1.0-dev.9.4 , angular-5.0.0 .

Not sure what most of the errors I'm getting are, but here's the Analyzer Diagnostics plugins section.

Plugins in use.

Analysis plugins

angular-5.0.0

bootstrap package path: /Users/g5ive/.pub-cache/hosted/pub.dartlang.org/angular-5.0.0/tools/analyzer_plugin

execution path: /Users/g5ive/.dartServer/.plugin_manager/40384d09db8185b9a8d3ac723b5c9a82/analyzer_plugin/bin/plugin.dart

packages file path: /Users/g5ive/.dartServer/.plugin_manager/40384d09db8185b9a8d3ac723b5c9a82/analyzer_plugin/.packages

IsolateSpawnException: Unable to spawn isolate: file:///Users/g5ive/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/expression_generator.dart:740:14: Error: The method 'ErroneousExpressionGenerator::buildCompoundAssignment' has fewer named arguments than those of overridden method 'KernelExpressionGenerator::buildCompoundAssignment'.
  Expression buildCompoundAssignment(Name binaryOperator, Expression value,
             ^
file:///Users/g5ive/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/kernel_expression_generator.dart:177:14: Context: This is the overridden method ('buildCompoundAssignment').
  Expression buildCompoundAssignment(Name binaryOperator, Expression value,
             ^
file:///Users/g5ive/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/kernel_expression_generator.dart:1424:7: Context: Override was introduced when the mixin 'ErroneousExpressionGenerator' was applied to 'KernelGenerator'.
class KernelUnresolvedNameGenerator extends KernelGenerator
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
file:///Users/g5ive/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/expression_generator.dart:740:14: Error: The method 'ErroneousExpressionGenerator::buildCompoundAssignment' doesn't have the named parameter 'isPostIncDec' of overridden method 'KernelExpressionGenerator::buildCompoundAssignment'.
  Expression buildCompoundAssignment(Name binaryOperator, Expression value,
             ^
file:///Users/g5ive/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/kernel_expression_generator.dart:177:14: Context: This is the overridden method ('buildCompoundAssignment').
  Expression buildCompoundAssignment(Name binaryOperator, Expression value,
             ^
file:///Users/g5ive/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/kernel_expression_generator.dart:1424:7: Context: Override was introduced when the mixin 'ErroneousExpressionGenerator' was applied to 'KernelGenerator'.
class KernelUnresolvedNameGenerator extends KernelGenerator
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
file:///Users/g5ive/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/expression_generator.dart:894:14: Error: The method 'ContextAwareGenerator::buildCompoundAssignment' has fewer named arguments than those of overridden method 'KernelExpressionGenerator::buildCompoundAssignment'.
  Expression buildCompoundAssignment(Name binaryOperator, Expression value,
             ^
file:///Users/g5ive/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/kernel_expression_generator.dart:177:14: Context: This is the overridden method ('buildCompoundAssignment').
  Expression buildCompoundAssignment(Name binaryOperator, Expression value,
             ^
file:///Users/g5ive/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/kernel_expression_generator.dart:1513:16: Context: Override was introduced when the mixin 'ContextAwareGenerator' was applied to 'KernelGenerator'.
abstract class KernelContextAwareGenerator extends KernelGenerator
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
file:///Users/g5ive/.pub-cache/hosted/pub.dartlang.org/front_end-0.1.4/lib/src/fasta/kernel/expression_generator.dart:894:14: Error: The method 'ContextAwareGenerator::buildCompoundAssignment' doesn't have the named parameter 'isPostIncDec' of overridden method 'KernelExpressionGenerator::buildCompoundAssignment'.
  Expression buildCompoundAssignment(Name binaryOperator, Expression value,
             ^
#0      Isolate.spawnUri (dart:isolate/runtime/libisolate_patch.dart:460:14)

#1      DiscoveredServerIsolateChannel._spawnIsolate (package:analyzer_plugin/src/channel/isolate_channel.dart:76:20)
#2      ServerIsolateChannel.listen (package:analyzer_plugin/src/channel/isolate_channel.dart:251:24)

#3      PluginSession.start (package:analysis_server/src/plugin/plugin_manager.dart:1077:20)

#4      PluginInfo.start (package:analysis_server/src/plugin/plugin_manager.dart:255:43)

#5      PluginManager.addPluginToContextRoot (package:analysis_server/src/plugin/plugin_manager.dart:403:48)

#6      PluginWatcher.addedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:78:19)
#7      AnalysisDriverScheduler.add (package:analyzer/src/dart/analysis/driver.dart:1798:22)
#8      new AnalysisDriver (package:analyzer/src/dart/analysis/driver.dart:352:16)
#9      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:177:33)
#10     ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:1127:48)
#11     ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1107:19)
#12     ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1147:16)
#13     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:737:9)
#14     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:819:22)
#15     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:385:14)
#16     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:299:16)
#17     AnalysisServer.handleRequest.. (package:analysis_server/src/analysis_server.dart:645:45)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#19     AnalysisServer.handleRequest. (package:analysis_server/src/analysis_server.dart:641:50)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1500:12)
#24     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:640:5)
#25     ByteStreamServerChannel._readRequest. (package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#26     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#27     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#28     ByteStreamServerChannel.listen. (package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#29     _rootRunUnary (dart:async/zone.dart:1132:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#36     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#37     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#38     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#39     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#40     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#41     _rootRunUnary (dart:async/zone.dart:1132:38)
#42     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#46     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#47     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#48     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#49     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#50     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#51     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#52     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#53     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#54     _rootRunUnary (dart:async/zone.dart:1132:38)
#55     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#59     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#60     _StreamController._add (dart:async/stream_controller.dart:639:7)
#61     _StreamController.add (dart:async/stream_controller.dart:585:5)
#62     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#63     _rootRunUnary (dart:async/zone.dart:1136:13)
#64     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#65     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#66     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#67     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#68     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#69     _StreamController._add (dart:async/stream_controller.dart:639:7)
#70     _StreamController.add (dart:async/stream_controller.dart:585:5)
#71     new _RawSocket. (dart:io/runtime/binsocket_patch.dart:1283:33)
#72     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#73     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#74     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#75     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#76     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by MichaelRFairhurst** [comment]
Thanks for reporting!!

Looks like we need to republish against a newer version of package:analyzer https://github.com/dart-lang/sdk/issues/34675

Current master just had some bug reports, but I will launch once those fixes are landed (#666 #665 , #664)
