### ISSUE TITLE
Bug found trying example project

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_analyzer_plugin#72]
https://github.com/akserg/angular.dart.ui.demo

Turns out this project is angular1 dart, but nonetheless ran into a issue that we should solve

```error: Exception from navigation contributor: AngularNavigationContributor
The null object does not have a getter 'offset'.

NoSuchMethodError: method not found: 'offset'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      AngularNavigationContributor._addDirectiveRegions (package:angular_analyzer_server_plugin/src/analysis.dart:94)
#3      AngularNavigationContributor.computeNavigation (package:angular_analyzer_server_plugin/src/analysis.dart:54)
#4      computeNavigation (package:analysis_server/src/domains/analysis/navigation.dart:28)
#5      sendAnalysisNotificationNavigation.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:203)
#6      _sendNotification.<anonymous closure> (package:analysis_server/src/operation/operation_analysis.dart:274)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#8      _sendNotification (package:analysis_server/src/operation/operation_analysis.dart:272)
#9      sendAnalysisNotificationNavigation (package:analysis_server/src/operation/operation_analysis.dart:201)
#10     NavigationOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:296)
#11     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:966)
#12     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#13     _rootRun (dart:async/zone.dart:1146)
#14     _CustomZone.run (dart:async/zone.dart:1026)
#15     _CustomZone.runGuarded (dart:async/zone.dart:924)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#17     _rootRun (dart:async/zone.dart:1150)
#18     _CustomZone.run (dart:async/zone.dart:1026)
#19     _CustomZone.runGuarded (dart:async/zone.dart:924)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#21     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#22     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#23     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

 
java.lang.Throwable
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
        at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.serverError(DartAnalysisServerService.java:208)
        at com.google.dart.server.internal.BroadcastAnalysisServerListener.serverError(BroadcastAnalysisServerListener.java:180)
        at com.google.dart.server.internal.remote.processor.NotificationServerErrorProcessor.process(NotificationServerErrorProcessor.java:37)
        at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:502)
        at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:517)
        at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:49)
        at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerI```

**Comment by MichaelRFairhurst** [comment]
This is angular dart 1.

Closing this.

**Comment by scheglov** [comment]
I don't think that crashing is OK with any code ;-)
Might be better to keep it even if with a lower priority.

**Comment by MichaelRFairhurst** [comment]
Ha, yes. Too focused on finding a project we can test it out on. Also this is in navigation, but its hard to know what all sideeffects this might have on other analysis stuff.

**Comment by MichaelRFairhurst** [comment]
Duplicate of better worded ticket #120
